const GET_ALL_USERS = 'GET_ALL_USERS'
const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE'


export { 
    GET_ALL_USERS,GET_ALL_USERS_SUCCESS,GET_ALL_USERS_FAILURE
}