require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Swing_Trading_Signals' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  # pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'Swing_Trading_SignalsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
  end
end

target 'Swing_Trading_Signals-tvOS' do
  # Pods for Swing_Trading_Signals-tvOS

  target 'Swing_Trading_Signals-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
